name: Build APK and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set Version Name as Environment Variable
        id: set_version_name
        shell: bash
        run: |
          VERSION_NAME=$(grep -o "versionName '.*'" build.gradle | cut -d "'" -f 2)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "Version Name: $VERSION_NAME"

      - name: Build with Gradle (All Variants)
        run: ./gradlew buildAllVariants

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: AccS-v${{ env.VERSION_NAME }}-release.apk
          path: build/outputs/apk/release/AccS-v${{ env.VERSION_NAME }}-release.apk

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AccS-v${{ env.VERSION_NAME }}-debug.apk
          path: build/outputs/apk/debug/AccS-v${{ env.VERSION_NAME }}-debug.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: Automated build v${{ env.VERSION_NAME }}
          draft: false
          prerelease: false

      - name: Set upload_url as an environment variable
        if: github.ref == 'refs/heads/main'
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Upload Release APK
        id: upload-release-apk
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: build/outputs/apk/release/AccS-v${{ env.VERSION_NAME }}-release.apk
          asset_name: AccS-v${{ env.VERSION_NAME }}-release.apk
          asset_content_type: application/zip

      - name: Upload Debug APK
        id: upload-debug-apk
        if: github.ref == 'refs/heads/main' && steps.create_release.outcome == 'success'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: build/outputs/apk/debug/AccS-v${{ env.VERSION_NAME }}-debug.apk
          asset_name: AccS-v${{ env.VERSION_NAME }}-debug.apk
          asset_content_type: application/zip